version: "3"
services:
  jupyter:
    build: .
    container_name: ai-create-lyrics
    tty: true
    user: root
    ports:
      - 8888:8888
    volumes:
      - ../:/ai-create-lyrics
    working_dir: /ai-create-lyrics
    environment:
      - SHELL=/bin/bash
      - JUPYTER_ENABLE_LAB=yes
